services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - $HOME/.var/app/sh.ppy.osu/data/osu/files/:/data/files:ro
      - $HOME/Projects/clicking-circles-player/song.json:/data/song.json:ro
    restart: unless-stopped
    hostname: nginx
